# Generated by Django 2.2.12 on 2020-05-21 12:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_description', models.CharField(max_length=255)),
                ('step_hasargument', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('test_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('step_failed', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=255)),
                ('basestep_id', models.CharField(max_length=255)),
                ('basestep_name', models.CharField(max_length=255)),
                ('step_argument', models.CharField(max_length=255, null=True)),
                ('step_number', models.IntegerField()),
                ('step_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('test_description', models.CharField(max_length=255)),
                ('test_file_name', models.CharField(max_length=255, null=True)),
                ('test_url', models.CharField(max_length=255, null=True)),
                ('test_tries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('tests_done', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
