# Generated by Django 2.2.12 on 2020-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_answer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='test_answer_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
