# Generated by Django 2.2.12 on 2020-05-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0002_test_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('test_id', models.CharField(max_length=255)),
                ('step_number', models.IntegerField()),
                ('step_status', models.CharField(max_length=255)),
                ('step_action', models.CharField(max_length=255)),
                ('step_description', models.CharField(max_length=255)),
            ],
        ),
    ]
