# Generated by Django 2.2.12 on 2020-05-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0002_auto_20200521_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_steps',
            name='basestep_id',
        ),
    ]
