# Generated by Django 2.2.12 on 2020-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0003_remove_test_steps_basestep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_correct',
            field=models.IntegerField(default=0),
        ),
    ]
