# Generated by Django 2.2.12 on 2020-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0003_test_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('test_description', models.CharField(max_length=255)),
                ('test_tries', models.IntegerField()),
            ],
        ),
    ]
