# Generated by Django 2.2.12 on 2020-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0004_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_steps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_description', models.CharField(max_length=255)),
                ('step_hasargument', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='test_steps',
            old_name='step_status',
            new_name='step_argument',
        ),
    ]
