# Generated by Django 2.2.12 on 2020-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0004_tests_test_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tests_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
