# Generated by Django 2.2.12 on 2020-05-13 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0005_auto_20200513_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_steps',
            name='basestep_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_steps',
            name='basestep_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='tests_done',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='test_steps',
            name='step_argument',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
