# Generated by Django 2.2.12 on 2020-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0006_auto_20200524_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=255),
        ),
    ]
