# Generated by Django 2.2.12 on 2020-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0006_auto_20200513_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_steps',
            name='step_action',
        ),
    ]
