# Generated by Django 2.2.12 on 2020-05-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0008_auto_20200514_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_steps',
            name='test_name',
        ),
    ]
