# Generated by Django 2.2.12 on 2020-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0009_remove_test_steps_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_file_name',
            field=models.CharField(default='pruebauf5.html', max_length=255),
            preserve_default=False,
        ),
    ]
