# Generated by Django 2.2.12 on 2020-05-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0011_auto_20200516_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
