# Generated by Django 2.2.12 on 2020-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0012_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
