# Generated by Django 2.2.12 on 2020-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjudge', '0013_auto_20200520_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_tries',
            field=models.IntegerField(default=0),
        ),
    ]
