
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200515
    container_name: selenium-hub
    privileged: true
    ports:
      - "4444:4444"
    environment:
      GRID_BROWSER_TIMEOUT: 10
      GRID_TIMEOUT: 10

  chrome:
    image: selenium/node-chrome:3.141.59-20200515
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141.59-20200515
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    